<a href="https://colab.research.google.com/github/2714830587-xh/CLRS-GG/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PCA分析

**推广到一般情况**，
如果我们有n个特征，如何进行数据降维。

第一步：针对采样得到的m个样本，我们得到了一个n*m的样本数据矩阵 ； 
第二步：对每一个特征的取值，进行零均值化处理，如果这些特征不在一个数量级上，我们还应该将其除以标准差。 
第三步：利用预处理后的矩阵A，求个特征的协方差矩阵C=(n-1)AA^T： 
第四步：对协方差矩阵进行对角化处理，求得矩阵C的n个标准正交特征向量，并按照对应的特征值的大小依次排列。 
第五步：按照事先规定的主成分贡献度，提取满足该数值要求的前k个新构造的特征作为主成分，构造成数据压缩矩阵： ​ 
第六步：通过矩阵相乘PA实现前k个主成分的提取，将n维特征压缩到k维

1.零值化处理

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
x = [2,2,4,8,4] 
y = [2,6,6,8,8]
# .vstack垂直（按行）按顺序堆叠数组。
S1=np.vstack((x,y))
print(S1) 
print(np.cov(S1))
x = x - np.mean(x) 
y = y - np.mean(y)
S2=np.vstack((x,y))
print(S2) 
print(np.cov(S2))

[[2 2 4 8 4]
 [2 6 6 8 8]]
[[6. 4.]
 [4. 6.]]
[[-2. -2.  0.  4.  0.]
 [-4.  0.  0.  2.  2.]]
[[6. 4.]
 [4. 6.]]


In [ ]:
import numpy as np 
from scipy import linalg 
C = np.array([[6, 4], [4, 6]])
# 特征值 和 归一化（单位“长度”）特征向量
evalue, evector = linalg.eig(C) 
print(evalue) 
print(evector)

[10.+0.j  2.+0.j]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


将原始特征的采样值变换到两个新选取的投影基上，就得到新的一组特征取值

In [ ]:
import numpy as np 
x = [2,2,4,8,4] 
y = [2,6,6,8,8] 
x = x - np.mean(x) 
y = y - np.mean(y) 
A = np.vstack((x,y)) 
p_1 = [0.707, 0.707] 
p_2 = [-0.707, 0.707] 
P = np.vstack((p_1,p_2)) 
print(A) 
print(np.dot(P,A))

[[-2. -2.  0.  4.  0.]
 [-4.  0.  0.  2.  2.]]
[[-4.242 -1.414  0.     4.242  1.414]
 [-1.414  1.414  0.    -1.414  1.414]]


数据降维，就是要方差大的，包含信息量大例如本题的[0.707，0.707】方向上的特征的方差是2.5大于另外一个0.5的所以丢掉那个。那么如何衡量损失。用主组成贡献-就是求对角矩阵各特征值所占比例。例如2.5/（2.5+0.5）=83.3%数据压缩了50%信息损失了16.7%